name: eksperimen-mlflow
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.1.1
      - numpy==1.26.0
      - scikit-learn==1.3.2
      - joblib==1.3.2
      - mlflow==2.9.2
      - dagshub==0.6.3
      - matplotlib==3.8.1
      - seaborn==0.13.0
